/**
 * Data source for select input components containing all countries of the world (`country`)
 * together with their capital cities (`capitalCity`).
 */
export const countriesDataSource: { country: string, capitalCity: string }[] = [
  { country: 'Afghanistan', capitalCity: 'Kabul' },
  { country: 'Albania', capitalCity: 'Tirana' },
  { country: 'Algeria', capitalCity: 'Algiers' },
  { country: 'Andorra', capitalCity: 'Andorra la Vella' },
  { country: 'Angola', capitalCity: 'Luanda' },
  { country: 'Antigua & Barbuda', capitalCity: 'St. John\'s' },
  { country: 'Argentina', capitalCity: 'Buenos Aires' },
  { country: 'Armenia', capitalCity: 'Yerevan' },
  { country: 'Australia', capitalCity: 'Canberra' },
  { country: 'Austria', capitalCity: 'Vienna' },
  { country: 'Azerbaijan', capitalCity: 'Baku' },
  { country: 'Bahamas', capitalCity: 'Nassau' },
  { country: 'Bahrain', capitalCity: 'Manama' },
  { country: 'Bangladesh', capitalCity: 'Dhaka' },
  { country: 'Barbados', capitalCity: 'Bridgetown' },
  { country: 'Belarus', capitalCity: 'Minsk' },
  { country: 'Belgium', capitalCity: 'Brussels' },
  { country: 'Belize', capitalCity: 'Belmopan' },
  { country: 'Benin', capitalCity: 'Porto-Novo' },
  { country: 'Bhutan', capitalCity: 'Thimphu' },
  { country: 'Bolivia', capitalCity: 'La Paz' },
  { country: 'Bosnia & Herzegovina', capitalCity: 'Sarajevo' },
  { country: 'Botswana', capitalCity: 'Gaborone' },
  { country: 'Brazil', capitalCity: 'Brasília' },
  { country: 'Brunei', capitalCity: 'Bandar Seri Begawan' },
  { country: 'Bulgaria', capitalCity: 'Sofia' },
  { country: 'Burkina Faso', capitalCity: 'Ouagadougou' },
  { country: 'Burundi', capitalCity: 'Gitega' },
  { country: 'Cabo Verde', capitalCity: 'Praia' },
  { country: 'Cambodia', capitalCity: 'Phnom Penh' },
  { country: 'Cameroon', capitalCity: 'Yaoundé' },
  { country: 'Canada', capitalCity: 'Ottawa' },
  { country: 'Central African Republic', capitalCity: 'Bangui' },
  { country: 'Chad', capitalCity: 'N\'Djamena' },
  { country: 'Chile', capitalCity: 'Santiago' },
  { country: 'China', capitalCity: 'Beijing' },
  { country: 'Colombia', capitalCity: 'Bogotá' },
  { country: 'Comoros', capitalCity: 'Moroni' },
  { country: 'Congo', capitalCity: 'Brazzaville' },
  { country: 'Costa Rica', capitalCity: 'San José' },
  { country: 'Côte d\'Ivoire', capitalCity: 'Yamoussoukro' },
  { country: 'Croatia', capitalCity: 'Zagreb' },
  { country: 'Cuba', capitalCity: 'Havana' },
  { country: 'Cyprus', capitalCity: 'Nicosia' },
  { country: 'Czech Republic', capitalCity: 'Prague' },
  { country: 'Denmark', capitalCity: 'Copenhagen' },
  { country: 'Djibouti', capitalCity: 'Djibouti' },
  { country: 'Dominica', capitalCity: 'Roseau' },
  { country: 'Dominican Republic', capitalCity: 'Santo Domingo' },
  { country: 'DR Congo', capitalCity: 'Kinshasa' },
  { country: 'Ecuador', capitalCity: 'Quito' },
  { country: 'Egypt', capitalCity: 'Cairo' },
  { country: 'El Salvador', capitalCity: 'San Salvador' },
  { country: 'Equatorial Guinea', capitalCity: 'Malabo' },
  { country: 'Eritrea', capitalCity: 'Asmara' },
  { country: 'Estonia', capitalCity: 'Tallinn' },
  { country: 'Eswatini', capitalCity: 'Mbabane' },
  { country: 'Ethiopia', capitalCity: 'Addis Ababa' },
  { country: 'Fiji', capitalCity: 'Suva' },
  { country: 'Finland', capitalCity: 'Helsinki' },
  { country: 'France', capitalCity: 'Paris' },
  { country: 'Gabon', capitalCity: 'Libreville' },
  { country: 'Gambia', capitalCity: 'Banjul' },
  { country: 'Georgia', capitalCity: 'Tbilisi' },
  { country: 'Germany', capitalCity: 'Berlin' },
  { country: 'Ghana', capitalCity: 'Accra' },
  { country: 'Greece', capitalCity: 'Athens' },
  { country: 'Grenada', capitalCity: 'St. George\'s' },
  { country: 'Guatemala', capitalCity: 'Guatemala City' },
  { country: 'Guinea', capitalCity: 'Conakry' },
  { country: 'Guinea-Bissau', capitalCity: 'Bissau' },
  { country: 'Guyana', capitalCity: 'Georgetown' },
  { country: 'Haiti', capitalCity: 'Port-au-Prince' },
  { country: 'Holy See', capitalCity: 'Vatican City' },
  { country: 'Honduras', capitalCity: 'Tegucigalpa' },
  { country: 'Hungary', capitalCity: 'Budapest' },
  { country: 'Iceland', capitalCity: 'Reykjavik' },
  { country: 'India', capitalCity: 'New Delhi' },
  { country: 'Indonesia', capitalCity: 'Jakarta' },
  { country: 'Iran', capitalCity: 'Tehran' },
  { country: 'Iraq', capitalCity: 'Baghdad' },
  { country: 'Ireland', capitalCity: 'Dublin' },
  { country: 'Israel', capitalCity: 'Jerusalem' },
  { country: 'Italy', capitalCity: 'Rome' },
  { country: 'Jamaica', capitalCity: 'Kingston' },
  { country: 'Japan', capitalCity: 'Tokyo' },
  { country: 'Jordan', capitalCity: 'Amman' },
  { country: 'Kazakhstan', capitalCity: 'Nur-Sultan' },
  { country: 'Kenya', capitalCity: 'Nairobi' },
  { country: 'Kiribati', capitalCity: 'South Tarawa' },
  { country: 'Kuwait', capitalCity: 'Kuwait City' },
  { country: 'Kyrgyzstan', capitalCity: 'Bishkek' },
  { country: 'Laos', capitalCity: 'Vientiane' },
  { country: 'Latvia', capitalCity: 'Riga' },
  { country: 'Lebanon', capitalCity: 'Beirut' },
  { country: 'Lesotho', capitalCity: 'Maseru' },
  { country: 'Liberia', capitalCity: 'Monrovia' },
  { country: 'Libya', capitalCity: 'Tripoli' },
  { country: 'Liechtenstein', capitalCity: 'Vaduz' },
  { country: 'Lithuania', capitalCity: 'Vilnius' },
  { country: 'Luxembourg', capitalCity: 'Luxembourg City' },
  { country: 'Madagascar', capitalCity: 'Antananarivo' },
  { country: 'Malawi', capitalCity: 'Lilongwe' },
  { country: 'Malaysia', capitalCity: 'Kuala Lumpur' },
  { country: 'Maldives', capitalCity: 'Male' },
  { country: 'Mali', capitalCity: 'Bamako' },
  { country: 'Malta', capitalCity: 'Valletta' },
  { country: 'Marshall Islands', capitalCity: 'Majuro' },
  { country: 'Mauritania', capitalCity: 'Nouakchott' },
  { country: 'Mauritius', capitalCity: 'Port Louis' },
  { country: 'Mexico', capitalCity: 'Mexico City' },
  { country: 'Micronesia', capitalCity: 'Palikir' },
  { country: 'Moldova', capitalCity: 'Chisinau' },
  { country: 'Monaco', capitalCity: 'Monaco' },
  { country: 'Mongolia', capitalCity: 'Ulaanbaatar' },
  { country: 'Montenegro', capitalCity: 'Podgorica' },
  { country: 'Morocco', capitalCity: 'Rabat' },
  { country: 'Mozambique', capitalCity: 'Maputo' },
  { country: 'Myanmar', capitalCity: 'Naypyidaw' },
  { country: 'Namibia', capitalCity: 'Windhoek' },
  { country: 'Nauru', capitalCity: 'Yaren District' },
  { country: 'Nepal', capitalCity: 'Kathmandu' },
  { country: 'Netherlands', capitalCity: 'Amsterdam' },
  { country: 'New Zealand', capitalCity: 'Wellington' },
  { country: 'Nicaragua', capitalCity: 'Managua' },
  { country: 'Niger', capitalCity: 'Niamey' },
  { country: 'Nigeria', capitalCity: 'Abuja' },
  { country: 'North Korea', capitalCity: 'Pyongyang' },
  { country: 'North Macedonia', capitalCity: 'Skopje' },
  { country: 'Norway', capitalCity: 'Oslo' },
  { country: 'Oman', capitalCity: 'Muscat' },
  { country: 'Pakistan', capitalCity: 'Islamabad' },
  { country: 'Palau', capitalCity: 'Ngerulmud' },
  { country: 'Panama', capitalCity: 'Panama City' },
  { country: 'Papua New Guinea', capitalCity: 'Port Moresby' },
  { country: 'Paraguay', capitalCity: 'Asunción' },
  { country: 'Peru', capitalCity: 'Lima' },
  { country: 'Philippines', capitalCity: 'Manila' },
  { country: 'Poland', capitalCity: 'Warsaw' },
  { country: 'Portugal', capitalCity: 'Lisbon' },
  { country: 'Qatar', capitalCity: 'Doha' },
  { country: 'Romania', capitalCity: 'Bucharest' },
  { country: 'Russia', capitalCity: 'Moscow' },
  { country: 'Rwanda', capitalCity: 'Kigali' },
  { country: 'Saint Kitts & Nevis', capitalCity: 'Basseterre' },
  { country: 'Saint Lucia', capitalCity: 'Castries' },
  { country: 'Samoa', capitalCity: 'Apia' },
  { country: 'San Marino', capitalCity: 'San Marino' },
  { country: 'Sao Tome & Principe', capitalCity: 'São Tomé' },
  { country: 'Saudi Arabia', capitalCity: 'Riyadh' },
  { country: 'Senegal', capitalCity: 'Dakar' },
  { country: 'Serbia', capitalCity: 'Belgrade' },
  { country: 'Seychelles', capitalCity: 'Victoria' },
  { country: 'Sierra Leone', capitalCity: 'Freetown' },
  { country: 'Singapore', capitalCity: 'Singapore' },
  { country: 'Slovakia', capitalCity: 'Bratislava' },
  { country: 'Slovenia', capitalCity: 'Ljubljana' },
  { country: 'Solomon Islands', capitalCity: 'Honiara' },
  { country: 'Somalia', capitalCity: 'Mogadishu' },
  { country: 'South Africa', capitalCity: 'Cape Town' },
  { country: 'South Korea', capitalCity: 'Seoul' },
  { country: 'South Sudan', capitalCity: 'Juba' },
  { country: 'Spain', capitalCity: 'Madrid' },
  { country: 'Sri Lanka', capitalCity: 'Sri Jayawardenepura Kotte' },
  { country: 'St. Vincent & Grenadines', capitalCity: 'Kingstown' },
  { country: 'State of Palestine', capitalCity: 'Ramallah' },
  { country: 'Sudan', capitalCity: 'Khartoum' },
  { country: 'Suriname', capitalCity: 'Paramaribo' },
  { country: 'Sweden', capitalCity: 'Stockholm' },
  { country: 'Switzerland', capitalCity: 'Bern' },
  { country: 'Syria', capitalCity: 'Damascus' },
  { country: 'Tajikistan', capitalCity: 'Dushanbe' },
  { country: 'Tanzania', capitalCity: 'Dodoma' },
  { country: 'Thailand', capitalCity: 'Bangkok' },
  { country: 'Timor-Leste', capitalCity: 'Dili' },
  { country: 'Togo', capitalCity: 'Lomé' },
  { country: 'Tonga', capitalCity: 'Nuku\'alofa' },
  { country: 'Trinidad & Tobago', capitalCity: 'Port of Spain' },
  { country: 'Tunisia', capitalCity: 'Tunis' },
  { country: 'Turkey', capitalCity: 'Ankara' },
  { country: 'Turkmenistan', capitalCity: 'Ashgabat' },
  { country: 'Tuvalu', capitalCity: 'Funafuti' },
  { country: 'Uganda', capitalCity: 'Kampala' },
  { country: 'Ukraine', capitalCity: 'Kyiv' },
  { country: 'United Arab Emirates', capitalCity: 'Abu Dhabi' },
  { country: 'United Kingdom', capitalCity: 'London' },
  { country: 'United States', capitalCity: 'Washington DC' },
  { country: 'Uruguay', capitalCity: 'Montevideo' },
  { country: 'Uzbekistan', capitalCity: 'Tashkent' },
  { country: 'Vanuatu', capitalCity: 'Port Vila' },
  { country: 'Venezuela', capitalCity: 'Caracas' },
  { country: 'Vietnam', capitalCity: 'Hanoi' },
  { country: 'Yemen', capitalCity: 'Sana\'a' },
  { country: 'Zambia', capitalCity: 'Lusaka' },
  { country: 'Zimbabwe', capitalCity: 'Harare' },
];
