# This workflow runs 'npm install' and commits the updated package-lock.json.

name: npm install

on:
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # built distribution folder to the repository.
      contents: write

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Run npm install
      run: npm install

    - name: Git commit updated package-lock.json
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add package-lock.json
        git commit -m "GitHub Action: Updated package-lock.json"
        git push
